### ISSUE TITLE
CLI fails on generating ontologies 

### ISSUE THREAD

**Issue by AlexMikhalev** [ontola/atomic-server#983]
To replicate create a new project:

```
pnpm create vite my-release-page --template vanilla-ts
cd my-release-page
pnpm install
pnpm install -D @tomic/cli
npx ad-generate init
npx ad-generate ontologies (or pnpm exec ad-generate ontologies)
```
fails with:
```
my-release-page npx ad-generate ontologies           
Found 1 ontologies
file:///Users/alex/projects/my-release-page/node_modules/.pnpm/@tomic+cli@0.40.0_@tomic+lib@0.40.0/node_modules/@tomic/cli/bin/src/generateSubjectToNameMapping.js:9
    const name = reverseMapping[subject].split('.')[2];
                                         ^

TypeError: Cannot read properties of undefined (reading 'split')
    at propLine (file:///Users/alex/projects/my-release-page/node_modules/.pnpm/@tomic+cli@0.40.0_@tomic+lib@0.40.0/node_modules/@tomic/cli/bin/src/generateSubjectToNameMapping.js:9:42)
    at file:///Users/alex/projects/my-release-page/node_modules/.pnpm/@tomic+cli@0.40.0_@tomic+lib@0.40.0/node_modules/@tomic/cli/bin/src/generateSubjectToNameMapping.js:3:42
    at Array.map (<anonymous>)
    at generateSubjectToNameMapping (file:///Users/alex/projects/my-release-page/node_modules/.pnpm/@tomic+cli@0.40.0_@tomic+lib@0.40.0/node_modules/@tomic/cli/bin/src/generateSubjectToNameMapping.js:3:30)
    at generateOntology (file:///Users/alex/projects/my-release-page/node_modules/.pnpm/@tomic+cli@0.40.0_@tomic+lib@0.40.0/node_modules/@tomic/cli/bin/src/generateOntology.js:47:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Module.ontologiesCommand (file:///Users/alex/projects/my-release-page/node_modules/.pnpm/@tomic+cli@0.40.0_@tomic+lib@0.40.0/node_modules/@tomic/cli/bin/src/commands/ontologies.js:23:21)

Node.js v22.9.0
```
on mac m3

**Comment by joepio** [comment]
I tried with [this ontology](https://atomicdata.dev/ontology/core) and your steps but could not replicate.

Which ontology did you use?

**Comment by joepio** [comment]
This one right? https://common.terraphim.io/drive/h6grD0ID/ontology/learning-rust

**Comment by AlexMikhalev** [comment]
Yes.

**Comment by joepio** [comment]
Is merged!
